### ISSUE TITLE
test 6 ch

### ISSUE THREAD

**Issue by osmanis** [osmanis/os-sandbox#8]
- [ ] | Task           | Time required | Assigned to   | Current Status | Finished | 
- [ ] |----------------|---------------|---------------|----------------|-----------|
- [ ] | Calendar Cache | > 5 hours  | c | in progress | - [x] ok?
- [ ] | Object Cache   | > 5 hours  | c | in progress | [x] item1<br/>[ ] item2

- [ ] | Object Cache 2
   - akldsf
- [ ] | Object Cache 1
- [ ] | Object Cache 3

**Comment by georgehrke** [comment]
@osmanis Thx for blindly coping something and mentioning me. Much appreciated 👍
