### ISSUE TITLE
test table

### ISSUE THREAD

**Issue by osmanis** [osmanis/os-sandbox#9]
| Task           | Time required | Assigned to   | Current Status | Finished | 
|----------------|---------------|---------------|----------------|-----------|
| Calendar Cache | > 5 hours  | 1 | in progress | - [x] ok?
- | Object Cache   | > 5 hours  | 2 | in progress | [x] item1<br/>[ ] item2

- [ ] | Object Cache 2
   - akldsf
- [ ] | Object Cache 1
- [ ] | Object Cache 3

**Comment by georgehrke** [comment]
@osmanis Where did you copy this table from?

**Comment by osmanis** [comment]
@georgehrke sorry didn't realized your name was tagged!

https://stackoverflow.com/questions/47344571/how-to-draw-checkbox-or-tick-mark-in-github-markdown-table
